/**
 * The TypeScript mirror of the content definitions, assembled from Rust.
 *
 * Two generators feed this module and neither of them parses Rust. `ts-rs`
 * derives the *shapes* from the definition structs themselves, one file per
 * schema; `crates/world/src/ts_export.rs` publishes the *bounds*, with the
 * values the compiler resolved and the documentation the author wrote. This
 * module puts the two halves together and dresses the result as source the
 * repository can read — which is all it does: it renders nothing it was not
 * handed, so a type that is wrong here is wrong in `crates/world`.
 *
 * See `.scratch/module-depth/issues/03-derive-content-types-from-definitions.md`
 * and `docs/adr/ADR-0012-shared-content-validation.md`.
 */

/** The banner every assembled module opens with. */
const BANNER = [
  '// @generated by `node scripts/generate-content-types.mjs` from `crates/world/src/`.',
  '// Edit the Rust definitions, not this file — `npm run check:types` fails on a stale copy.',
];

/** The banner `ts-rs` writes, which the one above replaces. */
const TS_RS_BANNER = /^\/\/ This file was generated by \[ts-rs\].*\n/;

/**
 * One bound, as a documented `export const`.
 *
 * The value arrives already rendered as TypeScript, so nothing here decides how
 * a number prints — `TsValue` in `crates/world/src/ts_export.rs` does, and it is
 * the side that knows whether `0.55` was an `f32`.
 */
export function renderBoundaryValue({ name, doc, value }) {
  const declaration = `export const ${name} = ${value};`;
  if (!doc) return declaration;

  const lines = doc.split('\n');
  if (lines.length === 1) return `/** ${lines[0]} */\n${declaration}`;

  const block = ['/**', ...lines.map((line) => (line ? ` * ${line}` : ' *')), ' */'];
  return `${block.join('\n')}\n${declaration}`;
}

/**
 * The bounds grouped by the module they belong in, declaration order kept.
 *
 * Order is the author's: `MIN_ELEVATION` reads before `MAX_ELEVATION` because
 * `definition.rs` declares it first, and a generated file that reshuffles its
 * own contents between runs cannot be checked for staleness.
 */
export function valuesByModule(values) {
  const grouped = new Map();
  for (const value of values) {
    const list = grouped.get(value.module);
    if (list) list.push(value);
    else grouped.set(value.module, [value]);
  }
  return grouped;
}

/**
 * One finished module: the banner, the imports, the bounds, then the shapes.
 *
 * The bounds go above the shapes because that is the order they are read in —
 * `MAX_TILE_IMAGE_SIZE` explains the field that is bounded by it — and because
 * `ts-rs` keeps its own imports on the first lines, where TypeScript wants them.
 */
export function assembleModule(name, generated, values) {
  const body = generated.replace(TS_RS_BANNER, '').trimStart();

  const lines = body.split('\n');
  const afterImports = lines.findIndex((line) => !line.startsWith('import '));
  const imports = lines.slice(0, afterImports).join('\n');
  const shapes = lines.slice(afterImports).join('\n').trimStart();

  const bounds = values.map(renderBoundaryValue).join('\n\n');

  return [BANNER.join('\n'), imports, bounds, shapes]
    .filter((section) => section.length > 0)
    .join('\n\n')
    .replace(/\n{3,}/g, '\n\n')
    .concat('\n');
}
