import { strict as assert } from 'node:assert';
import { describe, it } from 'node:test';

import { assembleModule, renderBoundaryValue, valuesByModule } from './content-types.mjs';

/** What `ts-rs` writes, down to its banner and its import line. */
const GENERATED = `// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OffsetCoord } from "./shared";

/**
 * A cell whose tile differs from the default.
 */
export type PlacedTile = { at: OffsetCoord, tile: string, };
`;

describe('renderBoundaryValue', () => {
  it('carries the documentation across as a doc block', () => {
    const rendered = renderBoundaryValue({
      name: 'MAX_ELEVATION',
      doc: 'Highest authored elevation.\n\nPacked as one signed byte per cell.',
      value: '127',
    });

    assert.equal(
      rendered,
      [
        '/**',
        ' * Highest authored elevation.',
        ' *',
        ' * Packed as one signed byte per cell.',
        ' */',
        'export const MAX_ELEVATION = 127;',
      ].join('\n'),
    );
  });

  it('writes a one-line document on one line', () => {
    const rendered = renderBoundaryValue({ name: 'MAX_STACK_SIZE', doc: 'Deepest stack.', value: '9999' });
    assert.equal(rendered, '/** Deepest stack. */\nexport const MAX_STACK_SIZE = 9999;');
  });

  it('leaves an undocumented bound bare rather than emitting an empty block', () => {
    assert.equal(renderBoundaryValue({ name: 'X', doc: '', value: '1' }), 'export const X = 1;');
  });
});

describe('valuesByModule', () => {
  it('groups the bounds by the module they belong in, in declaration order', () => {
    const grouped = valuesByModule([
      { module: 'world.ts', name: 'B', doc: '', value: '2' },
      { module: 'object.ts', name: 'C', doc: '', value: '3' },
      { module: 'world.ts', name: 'A', doc: '', value: '1' },
    ]);

    assert.deepEqual([...grouped.keys()], ['world.ts', 'object.ts']);
    assert.deepEqual(
      grouped.get('world.ts').map((value) => value.name),
      ['B', 'A'],
    );
  });
});

describe('assembleModule', () => {
  it('keeps an import that wraps over several lines whole', () => {
    const wrapped = `import type {\n  OffsetCoord,\n  PixelOffset,\n} from "./shared";\n\nexport type PlacedTile = { at: OffsetCoord };\n`;

    const assembled = assembleModule('world.ts', wrapped, [
      { name: 'MAX_ELEVATION', doc: '', value: '127' },
    ]);

    assert.match(assembled, /} from ".\/shared";\n\nexport const MAX_ELEVATION/);
    assert.ok(assembled.indexOf('PixelOffset,') < assembled.indexOf('MAX_ELEVATION'));
  });

  it('writes a module that is imports and nothing else without losing a line', () => {
    const assembled = assembleModule('world.ts', 'import type { A } from "./a";\n', []);

    assert.match(assembled, /import type \{ A \} from ".\/a";\n$/);
  });

  it('replaces the ts-rs banner with one naming the command that rewrites it', () => {
    const assembled = assembleModule('world.ts', GENERATED, []);

    assert.match(assembled, /^\/\/ @generated by `node scripts\/generate-content-types\.mjs`/);
    assert.doesNotMatch(assembled, /Aleph-Alpha/);
    assert.match(assembled, /npm run check:types/);
  });

  it('puts the bounds after the imports and before the types', () => {
    const assembled = assembleModule('world.ts', GENERATED, [
      { name: 'MAX_ELEVATION', doc: 'Highest.', value: '127' },
    ]);

    const importAt = assembled.indexOf('import type');
    const boundAt = assembled.indexOf('export const MAX_ELEVATION');
    const typeAt = assembled.indexOf('export type PlacedTile');

    assert.ok(importAt < boundAt, 'the import block stays at the top');
    assert.ok(boundAt < typeAt, 'a bound reads before the shapes that use it');
  });

  it('keeps the types and their documentation untouched', () => {
    const assembled = assembleModule('world.ts', GENERATED, []);

    assert.match(assembled, /A cell whose tile differs from the default\./);
    assert.match(assembled, /export type PlacedTile = \{ at: OffsetCoord, tile: string, \};/);
    assert.match(assembled, /import type \{ OffsetCoord \} from ".\/shared";/);
  });

  it('assembles a module that has no imports at all', () => {
    const bare = `// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ObjectKind = "consumable" | "other";
`;
    const assembled = assembleModule('object.ts', bare, [
      { name: 'MAX_STACK_SIZE', doc: '', value: '9999' },
    ]);

    assert.ok(
      assembled.indexOf('export const MAX_STACK_SIZE') < assembled.indexOf('export type ObjectKind'),
      'the bound still precedes the shapes',
    );
  });
});
