/**
 * The Angular↔engine seam, rendered from one declaration.
 *
 * `crates/engine/seam.json` states each boundary method once — its name, its
 * parameters, what it returns and what it does. This module turns that
 * declaration into the four copies that used to be written by hand: the
 * `JsonEngine` facade, the `wasm-bindgen` methods, the `RawInsulaireEngine`
 * TypeScript declarations and the method table in `docs/wasm-api.md`.
 *
 * See `.scratch/module-depth/issues/01-declare-the-engine-seam-once.md` and
 * `docs/adr/ADR-0010-engine-api.md`.
 */

/** Where the declaration lives, as a URL so callers need no path arithmetic. */
export const SEAM_PATH = new URL('../crates/engine/seam.json', import.meta.url);

/** The banner every generated file opens with. */
const BANNER = [
  '// @generated by `node scripts/generate-seam.mjs` from `crates/engine/seam.json`.',
  '// Edit the declaration, not this file — `npm run check:seam` fails on a stale copy.',
];

/** What a parameter is, in each of the three languages the seam crosses. */
const PARAM_TYPES = {
  str: { json: '&str', wasm: '&str', lend: (name) => name, ts: 'string', optional: false },
  'str?': {
    json: 'Option<&str>',
    wasm: 'Option<String>',
    lend: (name) => `${name}.as_deref()`,
    ts: 'string | undefined',
    optional: true,
  },
  u32: { json: 'u32', wasm: 'u32', lend: (name) => name, ts: 'number', optional: false },
  i32: { json: 'i32', wasm: 'i32', lend: (name) => name, ts: 'number', optional: false },
};

/** What a method gives back. `fallible` methods carry an error payload. */
const RETURN_TYPES = {
  json: { json: 'JsonResult', wasm: 'Result<String, JsValue>', ts: 'string', fallible: true },
  bytes_u8: {
    json: 'JsonResult<Vec<u8>>',
    wasm: 'Result<Vec<u8>, JsValue>',
    ts: 'Uint8Array',
    fallible: true,
  },
  bytes_i8: {
    json: 'JsonResult<Vec<i8>>',
    wasm: 'Result<Vec<i8>, JsValue>',
    ts: 'Int8Array',
    fallible: true,
  },
  void: { json: null, wasm: null, ts: 'void', fallible: false },
  bool: { json: 'bool', wasm: 'bool', ts: 'boolean', fallible: false },
};

/** Prettier's print width for `apps/web`, which the generated TypeScript obeys. */
const PRINT_WIDTH = 100;

/** Clippy warns above seven arguments; the receiver counts as one. */
const TOO_MANY_ARGUMENTS = 7;

/** Why a boundary method is allowed to be as wide as it is. */
const WIDE_METHOD_ALLOW =
  '#[allow(clippy::too_many_arguments)] // a wire, not an API: every field the boundary carries is a parameter';

/** Whether clippy would complain about this method's argument count. */
const isWide = (method) => method.params.length + 1 > TOO_MANY_ARGUMENTS;

/** `load_tile_set` is `loadTileSet` on the JavaScript side of the boundary. */
export function camelCase(name) {
  return name.replace(/_([a-z0-9])/g, (_, character) => character.toUpperCase());
}

/** `character_creation` is the `CharacterCreation` type parameter. */
function pascalCase(name) {
  return name.replace(/(^|_)([a-z0-9])/g, (_, __, character) => character.toUpperCase());
}

/**
 * What a content kind owes the boundary, as one method each.
 *
 * A kind is loaded, validated, read back and — when a project may hold many of
 * them — listed. `insulaire_engine` writes those four once, over a
 * `ContentKind`, so the boundary declares them once too: a row in `methods`
 * with a `kind` expands here into the methods that kind has, and the engine
 * call each makes is the generic one with the kind as its type parameter.
 *
 * Anything that is *not* one of the four stays an ordinary row — a decoration's
 * validation takes a cell no load can supply, a character resolves against a
 * customisation. Those differ per kind, which is exactly why they are not here.
 */
const KIND_METHODS = {
  load: (kind) => ({
    name: `load_${kind.kind}`,
    mutates: true,
    params: [{ name: 'json', type: 'str' }],
    returns: 'json',
    payload: 'LoadOutcome',
    inner: 'load',
    doc: [`Parses, validates and registers ${kind.noun}. Returns a {crate::LoadOutcome}.`],
    errors: [
      `\`parse\` for malformed JSON, \`invalidContent\` for a failing ${kind.bare}.`,
    ],
  }),
  validate: (kind) => ({
    name: `validate_${kind.kind}`,
    params: [{ name: 'json', type: 'str' }],
    returns: 'json',
    payload: 'ValidationReport',
    inner: 'validate',
    doc: [
      `Validates ${kind.noun} **without** registering it${
        kind.keys ? ', keys included' : ''
      }. Returns a \`ValidationReport\`.`,
    ],
    errors: ['`parse` for malformed JSON.'],
  }),
  get: (kind) => ({
    name: kind.kind,
    params: kind.read === 'by_id' ? [{ name: 'id', type: 'str' }] : [],
    returns: 'json',
    payload: kind.payload,
    inner: kind.read === 'by_id' ? 'definition' : 'only',
    doc:
      kind.read === 'by_id'
        ? [`Returns a registered {insulaire_world::${kind.payload}}.`]
        : [`Returns the registered \`${kind.payload}\`.`],
    errors:
      kind.read === 'by_id'
        ? ['`unknownContent` when no definition has that id.']
        : [`\`unknownContent\` when the project declares no ${kind.bare}.`],
  }),
  ids: (kind) => ({
    name: `${kind.kind}_ids`,
    params: [],
    returns: 'json',
    payload: 'string[]',
    infallible: true,
    inner: 'ids',
    doc: [`Returns the ids of every registered ${kind.bare}.`],
    errors: ['Only on serialisation failure.'],
  }),
};

/**
 * What each way of reading a kind back allows.
 *
 * This is about the *boundary*, not about the registry: a tile set is a `Many`
 * in Rust and still `none` here, because nothing across the boundary asks for
 * one by id — a world view carries what a renderer needs of it.
 */
const READ_METHODS = {
  by_id: ['load', 'validate', 'get', 'ids'],
  sole: ['load', 'validate', 'get'],
  none: ['load', 'validate'],
};

/**
 * Turns one content-kind row into the methods it declares.
 *
 * The row says which of them it wants, because not every kind owes all four: a
 * tile set is never read back by id, and a decoration is validated against a
 * cell no load can supply, so those keep a door of their own. What a row may
 * *not* do is invent a fifth shape — an unknown name here is a gate failure.
 */
function expandKind(row) {
  const where = `seam kind \`${row.kind}\``;
  const allowed = READ_METHODS[row.read];
  if (!allowed) throw new Error(`${where} has unknown read shape \`${row.read}\``);
  if (!row.noun) throw new Error(`${where} must say what prose calls it`);
  if (!row.payload) throw new Error(`${where} must name the definition it parses into`);
  if (!Array.isArray(row.methods) || row.methods.length === 0) {
    throw new Error(`${where} declares no methods`);
  }

  const kind = { ...row, bare: row.noun.replace(/^(a|an|the) /, '') };
  const type = `crate::kinds::${pascalCase(row.kind)}`;

  return row.methods.map((name) => {
    if (!allowed.includes(name)) {
      throw new Error(`${where} is read \`${row.read}\`, which has no \`${name}\``);
    }
    const method = KIND_METHODS[name](kind);
    const override = row[name] ?? {};
    return { ...method, ...override, generic: type };
  });
}

/**
 * Reads a declaration and refuses one the targets could not render.
 *
 * Every rule here is a copy that used to drift silently: a parameter type no
 * target knows, a fallible method with no documented errors, a payload the
 * reference cannot name.
 */
export function loadSeam(declaration) {
  const seen = new Set();
  const declared = declaration.methods.flatMap((entry) =>
    entry.kind ? expandKind(entry) : [entry],
  );
  const methods = declared.map((method) => {
    const where = `seam method \`${method.name}\``;
    if (seen.has(method.name)) throw new Error(`${where} is declared twice`);
    seen.add(method.name);

    const returns = RETURN_TYPES[method.returns];
    if (!returns) throw new Error(`${where} has unknown return shape \`${method.returns}\``);

    const params = (method.params ?? []).map((param) => {
      const type = PARAM_TYPES[param.type];
      if (!type) throw new Error(`${where} has unknown parameter type \`${param.type}\``);
      return { ...param, jsName: camelCase(param.name), type: param.type, types: type };
    });

    if (returns.fallible && !method.errors?.length) {
      throw new Error(`${where} must document its errors`);
    }
    if (!returns.fallible && method.errors?.length) {
      throw new Error(`${where} returns \`${method.returns}\` and so cannot fail`);
    }
    if (method.returns === 'json' && !method.payload) {
      throw new Error(`${where} must name the payload it encodes`);
    }
    if (method.returns !== 'json' && method.payload) {
      throw new Error(`${where} returns \`${method.returns}\`, which already names itself`);
    }
    if (method.expr && method.returns !== 'json') {
      throw new Error(`${where} has an \`expr\`, which only a \`json\` return can encode`);
    }
    if (!method.doc?.length) throw new Error(`${where} must be documented`);

    return {
      ...method,
      params,
      returns: method.returns,
      types: returns,
      jsName: camelCase(method.name),
      inner: method.inner ?? method.name,
      receiver: method.mutates ? '&mut self' : '&self',
    };
  });

  return { modules: declaration.modules, methods };
}

// ---------------------------------------------------------------- doc comments

/**
 * Renders `{crate::LoadOutcome}` for one target.
 *
 * The declaration names a type by its Rust path. `insulaire-engine` can link to
 * it, the WASM crate and the TypeScript cannot, so they get the bare name.
 */
function resolveLinks(text, { linked }) {
  return text.replace(/\{([\w:]+)\}/g, (_, path) => {
    const name = path.slice(path.lastIndexOf(':') + 1);
    return linked ? `[\`${name}\`](${path})` : `\`${name}\``;
  });
}

/**
 * Spells a parameter the way the reader of a Rust doc comment expects it.
 *
 * One doc serves both Rust copies, and the text it was reconciled from named
 * its arguments in JavaScript. Only names the method actually declares move.
 */
function resolveNames(text, method) {
  return text.replace(/`(\w+)`/g, (whole, word) => {
    const param = method.params.find((p) => p.name === word || p.jsName === word);
    return param ? `\`${param.name}\`` : whole;
  });
}

/** A method's doc comment, wrapped as `///` lines with its errors section. */
function docComment(method, { linked, indent }) {
  const render = (line) => resolveNames(resolveLinks(line, { linked }), method);
  const paragraphs = method.doc.map(render);
  if (method.errors?.length) {
    paragraphs.push('# Errors');
    paragraphs.push(...method.errors.map(render));
  }
  return paragraphs
    .map((paragraph) => wrap(paragraph, 80 - indent.length - 4).map((line) => `/// ${line}`))
    .flatMap((lines, index) => (index === 0 ? lines : ['///', ...lines]))
    .map((line) => `${indent}${line.trimEnd()}`)
    .join('\n');
}

/**
 * A module's `//!` header.
 *
 * The prose is authored, but it resolves `{crate::Type}` and rewraps the same
 * way a method's doc does: a header naming a type should link to it, and a link
 * is three times longer than the name it replaces. Blank lines separate
 * paragraphs, so a heading or a break in the authored text survives.
 */
function moduleDoc(module, { linked }) {
  return paragraphsOf(module.doc)
    .map((paragraph) => wrap(resolveLinks(paragraph, { linked }), 80 - 4))
    .flatMap((lines, index) => (index === 0 ? lines : ['', ...lines]))
    .map((line) => `//! ${line}`.trimEnd())
    .join('\n');
}

/** Groups authored lines into paragraphs on blank lines. */
function paragraphsOf(lines) {
  const paragraphs = [];
  let current = [];
  for (const line of lines) {
    if (line.trim() === '') {
      if (current.length) paragraphs.push(current.join(' '));
      current = [];
      continue;
    }
    current.push(line.trim());
  }
  if (current.length) paragraphs.push(current.join(' '));
  return paragraphs;
}

/** Greedy wrap; rustfmt leaves doc comments alone, so this is the last word. */
function wrap(text, width) {
  const lines = [];
  let current = '';
  for (const word of text.split(' ')) {
    if (current && `${current} ${word}`.length > width) {
      lines.push(current);
      current = word;
    } else {
      current = current ? `${current} ${word}` : word;
    }
  }
  if (current) lines.push(current);
  return lines;
}

// ------------------------------------------------------------ the JSON facade

/** The whole of `crates/engine/src/json.rs`. */
export function renderJsonEngine(seam) {
  // `Engine` and `EngineError` are always used — by the struct and by `err`.
  // An adapted parameter may need the type it parses into as well.
  const imports = new Set(['crate::Engine', 'crate::error::EngineError']);
  for (const method of seam.methods) {
    for (const param of method.params) {
      if (param.adapt?.import) imports.add(param.adapt.import);
    }
  }

  const methods = seam.methods.map((method) => renderJsonMethod(method)).join('\n\n');

  return `${BANNER.join('\n')}

${moduleDoc(seam.modules.json, { linked: true })}

${[...imports].sort().map((path) => `use ${path};`).join('\n')}

/// The result of a facade call: JSON on success, a serialised
/// [\`EngineErrorPayload\`](crate::EngineErrorPayload) on failure.
pub type JsonResult<T = String> = Result<T, String>;

/// Serialises \`value\`, or reports the failure in the same error shape.
fn ok<T: serde::Serialize>(value: &T) -> JsonResult {
    serde_json::to_string(value).map_err(|error| {
        let message =
            serde_json::to_string(&error.to_string()).unwrap_or_else(|_| "\\"unknown\\"".to_owned());
        format!(r#"{{"code":"serialise","message":{message}}}"#)
    })
}

/// Renders an engine error as its JSON payload.
fn err(error: &EngineError) -> String {
    serde_json::to_string(&error.to_payload())
        .unwrap_or_else(|_| r#"{"code":"unknown","message":"engine error"}"#.to_owned())
}

/// [\`Engine\`] with a string boundary.
#[derive(Debug, Default)]
pub struct JsonEngine {
    inner: Engine,
}

impl JsonEngine {
    /// Creates an engine with an empty content registry.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

${methods}
}

#[cfg(test)]
mod tests;
`;
}

function renderJsonMethod(method) {
  const indent = '    ';
  const signature = [
    `pub ${method.returns === 'bool' ? 'const ' : ''}fn ${method.name}(`,
    [method.receiver, ...method.params.map((p) => `${p.name}: ${p.types.json}`)].join(', '),
    ')',
    method.types.json ? ` -> ${method.types.json}` : '',
  ].join('');

  const attributes = [
    ...(isWide(method) ? [WIDE_METHOD_ALLOW] : []),
    ...(method.returns === 'bool' ? ['#[must_use]'] : []),
  ];
  const args = method.params.map((p) => p.adapt?.as ?? p.name).join(', ');
  // A content kind reaches the engine through the generic method, with itself
  // as the type parameter; everything else names an engine method of its own.
  const turbofish = method.generic ? `::<${method.generic}>` : '';
  const call = method.expr ?? `self.inner.${method.inner}${turbofish}(${args})`;

  const lines = method.params.filter((p) => p.adapt).map((param) => adaptInJson(param));
  if (method.expr) {
    lines.push(`ok(&${method.expr})`);
  } else if (method.returns === 'json') {
    lines.push(
      method.infallible
        ? `ok(&${call})`
        : `let value = ${call}.map_err(|error| err(&error))?;\nok(&value)`,
    );
  } else if (method.returns === 'bytes_u8' || method.returns === 'bytes_i8') {
    lines.push(`${call}.map_err(|error| err(&error))`);
  } else if (method.returns === 'void') {
    lines.push(`${call};`);
  } else {
    lines.push(call);
  }

  const body = lines
    .join('\n')
    .split('\n')
    .map((line) => `${indent}${indent}${line}`.trimEnd())
    .join('\n');

  return [
    docComment(method, { linked: true, indent }),
    ...attributes.map((attribute) => `${indent}${attribute}`),
    `${indent}${signature} {`,
    body,
    `${indent}}`,
  ].join('\n');
}

/**
 * A parameter that crosses as a string but is typed inside.
 *
 * The parse belongs to the facade rather than to `Engine`: the typed engine
 * takes the typed value, and the boundary is where a bad string becomes a
 * `parse` error payload.
 */
function adaptInJson(param) {
  const binding = param.adapt.as ?? param.name;
  const what = param.adapt.what;
  if (param.adapt.from === 'json') {
    return `let ${binding}: ${param.adapt.type} = serde_json::from_str(${param.name}).map_err(|error| {
    err(&EngineError::Parse {
        what: "${what}".to_owned(),
        message: error.to_string(),
    })
})?;`;
  }
  return `let ${binding} = ${param.name}.parse().map_err(|message| {
    err(&EngineError::Parse {
        what: "${what}".to_owned(),
        message,
    })
})?;`;
}

// ----------------------------------------------------------- the WASM bindings

/** The whole of `crates/wasm/src/lib.rs`. */
export function renderWasmBindings(seam) {
  const methods = seam.methods.map((method) => renderWasmMethod(method)).join('\n\n');

  return `${BANNER.join('\n')}

${moduleDoc(seam.modules.wasm, { linked: false })}

${(seam.modules.wasm.attrs ?? []).join('\n')}

use insulaire_engine::JsonEngine;
use wasm_bindgen::prelude::*;

/// Installs a panic hook so Rust panics surface as readable console errors
/// instead of \`unreachable executed\`.
#[wasm_bindgen(start)]
pub fn start() {
    console_error_panic_hook::set_once();
}

fn to_js(error: String) -> JsValue {
    JsValue::from_str(&error)
}

/// The engine, as seen from JavaScript.
///
/// One instance owns one content registry and at most one running game.
/// Every method that can fail rejects with a JSON string of the shape
/// \`{ "code": "...", "message": "...", "report"?: { ... } }\`.
#[wasm_bindgen]
#[derive(Debug, Default)]
pub struct InsulaireEngine {
    inner: JsonEngine,
}

#[wasm_bindgen]
impl InsulaireEngine {
    /// Creates an engine with an empty content registry.
    #[wasm_bindgen(constructor)]
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

${methods}
}
`;
}

function renderWasmMethod(method) {
  const indent = '    ';
  const signature = [
    `pub fn ${method.name}(`,
    [method.receiver, ...method.params.map((p) => `${p.name}: ${p.types.wasm}`)].join(', '),
    ')',
    method.types.wasm ? ` -> ${method.types.wasm}` : '',
  ].join('');

  const attributes = [`#[wasm_bindgen(js_name = ${method.jsName})]`];
  if (isWide(method)) attributes.push(WIDE_METHOD_ALLOW);
  if (method.returns === 'bool') attributes.push('#[must_use]');

  const args = method.params.map((p) => p.types.lend(p.name)).join(', ');
  const call = `self.inner.${method.name}(${args})`;
  const body = method.types.fallible
    ? `${call}.map_err(to_js)`
    : method.returns === 'void'
      ? `${call};`
      : call;

  return [
    docComment(method, { linked: false, indent }),
    ...attributes.map((attribute) => `${indent}${attribute}`),
    `${indent}${signature} {`,
    `${indent}${indent}${body}`,
    `${indent}}`,
  ].join('\n');
}

// -------------------------------------------------------- the TypeScript view

/** The `RawInsulaireEngine` interface, as the web app declares the boundary. */
export function renderRawEngineInterface(seam) {
  const methods = seam.methods.map((method) => renderTypeScriptMethod(method));
  const doc = seam.modules.typescript.doc;
  return [
    '/**',
    ...doc.map((line) => ` * ${line}`.trimEnd()),
    ' */',
    'export interface RawInsulaireEngine {',
    ...methods,
    '  /** Releases the Rust-side instance; `wasm-bindgen` adds it, the seam does not. */',
    '  free(): void;',
    '}',
  ].join('\n');
}

function renderTypeScriptMethod(method) {
  const params = method.params.map((p) => `${p.jsName}: ${p.types.ts}`);
  const oneLine = `  ${method.jsName}(${params.join(', ')}): ${method.types.ts};`;
  const documented = method.params.some((p) => p.doc);
  if (!documented && oneLine.length <= PRINT_WIDTH) return oneLine;

  const body = method.params.flatMap((param) => [
    ...(param.doc ? [`    /** ${param.doc} */`] : []),
    `    ${param.jsName}: ${param.types.ts},`,
  ]);
  return [`  ${method.jsName}(`, ...body, `  ): ${method.types.ts};`].join('\n');
}

// ------------------------------------------------------------- the fifth copy

/**
 * The seam methods `EngineService` never reaches.
 *
 * The service is not generated: it returns typed values, marshals its arguments
 * and documents itself for an Angular caller rather than for the boundary. What
 * it must not do is fall behind, which is what this catches — a method declared
 * and never wired through is the half-landing the declaration exists to stop.
 *
 * The reverse direction needs no check: `RawInsulaireEngine` is generated and
 * typed, so a call to a method the seam does not declare fails `tsc`.
 */
export function unwiredMethods(seam, source) {
  const code = withoutComments(source);
  return seam.methods
    .filter((method) => !code.includes(`.${method.jsName}(`))
    .map((method) => method.jsName);
}

/**
 * Drops comments, so a method named only in prose does not pass for wired.
 *
 * A doc comment mentioning `.snapshot()` is exactly the half-landing this
 * guard exists to catch, not evidence against it.
 */
function withoutComments(source) {
  return source.replace(/\/\*[\s\S]*?\*\//g, '').replace(/(^|[^:])\/\/.*$/gm, '$1');
}

// --------------------------------------------------------- the reference table

/**
 * The index of `docs/wasm-api.md`: one row per method, linking to its section.
 *
 * `headings` are the document's own `###` texts. A method with no section is an
 * error rather than a missing row — the prose is authored, and the point of the
 * table is that it cannot fall behind the declaration.
 */
export function renderMethodTable(seam, headings) {
  const anchors = new Map();
  for (const heading of headings) {
    // One section may cover two methods, as `endGame` and `hasGame` do.
    for (const part of heading.split(' / ')) {
      const name = part.replaceAll('`', '').slice(0, part.replaceAll('`', '').indexOf('('));
      if (name) anchors.set(name, anchorOf(heading));
    }
  }

  const rows = seam.methods.map((method) => {
    const anchor = anchors.get(method.jsName);
    if (!anchor) {
      throw new Error(`\`${method.jsName}\` has no \`###\` section in docs/wasm-api.md`);
    }
    const args = method.params
      .map((p) => `\`${p.jsName}${p.types.optional ? '?' : ''}\``)
      .join(', ');
    return `| [\`${method.jsName}\`](#${anchor}) | ${args || '—'} | \`${method.payload ?? method.types.ts}\` |`;
  });

  return ['| Method | Arguments | Returns |', '|---|---|---|', ...rows].join('\n');
}

/**
 * GitHub's heading anchor: lowercased, punctuation dropped, each space hyphenated.
 *
 * Runs of spaces are *not* collapsed — a heading covering two methods leaves two
 * of them where its separator was, and the anchor keeps both.
 */
function anchorOf(heading) {
  return heading
    .toLowerCase()
    .replace(/[^\w\- ]/g, '')
    .replace(/ /g, '-');
}
