// @generated by `node scripts/generate-seam.mjs` from `crates/engine/seam.json`.
// Edit the declaration, not this file — `npm run check:seam` fails on a stale copy.

//! The string-in / string-out facade.
//!
//! This is the *exact* contract the WASM bindings expose, expressed without any
//! dependency on `wasm-bindgen`. Structured payloads cross as JSON strings and
//! errors as serialised [`EngineErrorPayload`](crate::EngineErrorPayload)s; the
//! one bulk payload, the terrain buffer, stays a plain byte vector.
//!
//! Keeping the contract here rather than in `insulaire-wasm` means the whole
//! boundary is covered by ordinary `cargo test`, and the WASM crate reduces to
//! a pass-through that cannot hide a bug.
//!
//! # Why JSON strings
//!
//! Snapshots are a few hundred bytes, so the parse cost is irrelevant, and a
//! string boundary is trivially inspectable from devtools and from tests. The
//! payload that *is* large never uses JSON. See `docs/wasm-api.md`.

use crate::dto::Command;
use crate::error::EngineError;
use crate::Engine;

/// The result of a facade call: JSON on success, a serialised
/// [`EngineErrorPayload`](crate::EngineErrorPayload) on failure.
pub type JsonResult<T = String> = Result<T, String>;

/// Serialises `value`, or reports the failure in the same error shape.
fn ok<T: serde::Serialize>(value: &T) -> JsonResult {
    serde_json::to_string(value).map_err(|error| {
        let message =
            serde_json::to_string(&error.to_string()).unwrap_or_else(|_| "\"unknown\"".to_owned());
        format!(r#"{{"code":"serialise","message":{message}}}"#)
    })
}

/// Renders an engine error as its JSON payload.
fn err(error: &EngineError) -> String {
    serde_json::to_string(&error.to_payload())
        .unwrap_or_else(|_| r#"{"code":"unknown","message":"engine error"}"#.to_owned())
}

/// [`Engine`] with a string boundary.
#[derive(Debug, Default)]
pub struct JsonEngine {
    inner: Engine,
}

impl JsonEngine {
    /// Creates an engine with an empty content registry.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Build identity: name, version, target architecture, pointer width and
    /// supported schema versions.
    ///
    /// # Errors
    ///
    /// Only on serialisation failure.
    pub fn engine_info(&self) -> JsonResult {
        ok(&Engine::info())
    }

    /// Parses, validates and registers a tile set. Returns a
    /// [`LoadOutcome`](crate::LoadOutcome).
    ///
    /// # Errors
    ///
    /// `parse` for malformed JSON, `invalidContent` for a failing tile set.
    pub fn load_tile_set(&mut self, json: &str) -> JsonResult {
        let value = self
            .inner
            .load::<crate::kinds::TileSet>(json)
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Validates a tile set **without** registering it. Returns a
    /// `ValidationReport`.
    ///
    /// # Errors
    ///
    /// `parse` for malformed JSON.
    pub fn validate_tile_set(&self, json: &str) -> JsonResult {
        let value = self
            .inner
            .validate::<crate::kinds::TileSet>(json)
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Parses, validates and registers a world. Returns a
    /// [`LoadOutcome`](crate::LoadOutcome).
    ///
    /// # Errors
    ///
    /// `parse` for malformed JSON, `invalidContent` for a failing world. The
    /// error payload carries the full validation report.
    pub fn load_world(&mut self, json: &str) -> JsonResult {
        let value = self
            .inner
            .load::<crate::kinds::World>(json)
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Validates a world *without* registering it — the editor's pre-export
    /// check. Returns a `ValidationReport`.
    ///
    /// # Errors
    ///
    /// `parse` for malformed JSON. An unusable world yields an invalid report,
    /// not an error.
    pub fn validate_world(&self, json: &str) -> JsonResult {
        let value = self
            .inner
            .validate::<crate::kinds::World>(json)
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Parses, validates and registers the project manifest — the list of
    /// content files that make up the game, and the world it starts on. Returns
    /// a [`LoadOutcome`](crate::LoadOutcome).
    ///
    /// Call it after the content it lists has been loaded.
    ///
    /// # Errors
    ///
    /// `parse` for malformed JSON, `invalidContent` when it references content
    /// that is not loaded.
    pub fn load_project(&mut self, json: &str) -> JsonResult {
        let value = self
            .inner
            .load::<crate::kinds::Project>(json)
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Registers one locale file under a language and a namespace. Returns a
    /// [`LoadOutcome`](crate::LoadOutcome) whose id is `language/namespace`.
    ///
    /// # Errors
    ///
    /// `parse` when the file is not a nested object of strings, or redefines a
    /// key the language already has.
    pub fn load_locale(&mut self, language: &str, namespace: &str, json: &str) -> JsonResult {
        let value = self
            .inner
            .load_locale(language, namespace, json)
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Returns a [`LocaleView`](crate::LocaleView): one language's text, gaps
    /// filled by the default language.
    ///
    /// # Errors
    ///
    /// `unknownContent` when no file was loaded for that language.
    pub fn locale(&self, language: &str) -> JsonResult {
        let value = self.inner.locale(language).map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Compares the loaded languages against the manifest and each other.
    /// Returns a `ValidationReport`.
    ///
    /// # Errors
    ///
    /// Only on serialisation failure.
    pub fn validate_locales(&self) -> JsonResult {
        ok(&self.inner.validate_locales())
    }

    /// Registers the title screen a client opens on. Returns a
    /// [`LoadOutcome`](crate::LoadOutcome).
    ///
    /// # Errors
    ///
    /// `parse` for malformed JSON, `invalidContent` for a screen that cannot be
    /// shown — no visible `newGame` button, an asset path leaving the content
    /// root, a number out of range.
    pub fn load_title_screen(&mut self, json: &str) -> JsonResult {
        let value = self
            .inner
            .load::<crate::kinds::TitleScreen>(json)
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Validates a title screen **without** registering it, keys included.
    /// Returns a `ValidationReport`.
    ///
    /// # Errors
    ///
    /// `parse` for malformed JSON.
    pub fn validate_title_screen(&self, json: &str) -> JsonResult {
        let value = self
            .inner
            .validate::<crate::kinds::TitleScreen>(json)
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Returns the registered `TitleScreenDefinition`.
    ///
    /// # Errors
    ///
    /// `unknownContent` when the project declares no title screen.
    pub fn title_screen(&self) -> JsonResult {
        let value = self
            .inner
            .only::<crate::kinds::TitleScreen>()
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Resolves what to draw for one cell of a tile set **passed in** — the
    /// asset editor's preview, for content that is not registered yet. Returns
    /// a `ResolvedTileRender`.
    ///
    /// `base` is the height the cell's side faces reach down to; `roll` is the
    /// cell's variant roll
    /// (`docs/adr/ADR-0026-tile-art-is-authored-and-resolved-by-level.md`).
    /// `projection` is the world's own — `"isometric"` for the surface and the
    /// cliff, anything else for the flat image
    /// (`docs/adr/ADR-0026-tile-art-is-authored-and-resolved-by-level.md`).
    /// `choice_json` is a `PlacedTileArt` — what the cell picked by hand —
    /// resolved against the set passed in; `"{}"` rolls everything
    /// (`docs/adr/ADR-0026-tile-art-is-authored-and-resolved-by-level.md`).
    ///
    /// # Errors
    ///
    /// `parse` when either JSON is malformed, `unknownContent` when the set
    /// defines no tile with that id.
    #[allow(clippy::too_many_arguments)] // a wire, not an API: every field the boundary carries is a parameter
    pub fn preview_tile_render(
        &self,
        tile_set_json: &str,
        tile_id: &str,
        projection: &str,
        elevation: i32,
        base: i32,
        roll: u32,
        choice_json: &str,
    ) -> JsonResult {
        let value = self
            .inner
            .preview_tile_render(
                tile_set_json,
                tile_id,
                projection,
                elevation,
                base,
                roll,
                choice_json,
            )
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Forgets every loaded tile set, world, locale and project.
    ///
    /// Hosts call this before re-loading a whole project, so content removed in
    /// the editor stops answering for itself. A running game is unaffected.
    pub fn reset_content(&mut self) {
        self.inner.reset_content();
    }

    /// Forgets every loaded language, keeping worlds, tile sets and project.
    ///
    /// The language editor calls this before registering the files it just
    /// wrote: loading is additive and refuses a key twice, so edited text can
    /// only replace the old text once the old bundles are gone.
    pub fn reset_locales(&mut self) {
        self.inner.reset_locales();
    }

    /// Resolves every map link across the loaded worlds. Returns a
    /// `ValidationReport`.
    ///
    /// # Errors
    ///
    /// Only on serialisation failure.
    pub fn validate_links(&self) -> JsonResult {
        ok(&self.inner.validate_links())
    }

    /// Returns a [`ContentSummary`](crate::ContentSummary): loaded tile sets,
    /// worlds and templates.
    ///
    /// # Errors
    ///
    /// Only on serialisation failure.
    pub fn content_summary(&self) -> JsonResult {
        ok(&self.inner.content_summary())
    }

    /// Returns a [`WorldView`](crate::WorldView): dimensions, tile palette and
    /// locations.
    ///
    /// # Errors
    ///
    /// `unknownContent` when the world is not registered.
    pub fn world_view(&self, world_id: &str) -> JsonResult {
        let value = self
            .inner
            .world_view(world_id)
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Returns the packed terrain buffer as a `Uint8Array`: one palette index
    /// per cell, row-major in offset coordinates.
    ///
    /// This is one of the three bulk transfers in the API, and the reason the
    /// renderer never calls into WASM per tile.
    ///
    /// # Errors
    ///
    /// `unknownContent` when the world is not registered.
    pub fn terrain_buffer(&self, world_id: &str) -> JsonResult<Vec<u8>> {
        self.inner
            .terrain_buffer(world_id)
            .map_err(|error| err(&error))
    }

    /// Returns the packed elevation buffer as an `Int8Array`: one signed byte
    /// per cell, in the same layout as `terrainBuffer`.
    ///
    /// Presentation only; the renderer uses it in isometric mode
    /// (`docs/adr/ADR-0013-isometric-projection.md`).
    ///
    /// # Errors
    ///
    /// `unknownContent` when the world is not registered.
    pub fn elevation_buffer(&self, world_id: &str) -> JsonResult<Vec<i8>> {
        self.inner
            .elevation_buffer(world_id)
            .map_err(|error| err(&error))
    }

    /// Returns the packed presence buffer as a `Uint8Array`: `1` where the map
    /// has a hex, `0` where it has a hole, in the same layout as
    /// `terrainBuffer`.
    ///
    /// A map is a set of hexes, not a rectangle; the extent in
    /// `worldView().bounds` is only what the buffers cover
    /// (`docs/adr/ADR-0033-a-map-is-a-set-of-hexes.md`).
    ///
    /// # Errors
    ///
    /// `unknownContent` when the world is not registered.
    pub fn presence_buffer(&self, world_id: &str) -> JsonResult<Vec<u8>> {
        self.inner
            .presence_buffer(world_id)
            .map_err(|error| err(&error))
    }

    /// Starts a game on a registered world. Returns the initial
    /// [`GameSnapshot`](crate::GameSnapshot).
    ///
    /// # Errors
    ///
    /// `unknownContent` or `setup`.
    pub fn create_game(&mut self, world_id: &str, seed: u32, settings_json: &str) -> JsonResult {
        let value = self
            .inner
            .create_game(world_id, seed, settings_json)
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Registers the game's settings declaration. Returns a
    /// [`LoadOutcome`](crate::LoadOutcome).
    ///
    /// # Errors
    ///
    /// `parse` for malformed JSON, `invalidContent` for a declaration that
    /// cannot be rendered — a duplicate id, a default no control accepts.
    pub fn load_settings(&mut self, json: &str) -> JsonResult {
        let value = self
            .inner
            .load::<crate::kinds::Settings>(json)
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Validates a settings declaration **without** registering it, keys
    /// included. Returns a `ValidationReport`.
    ///
    /// # Errors
    ///
    /// `parse` for malformed JSON.
    pub fn validate_settings(&self, json: &str) -> JsonResult {
        let value = self
            .inner
            .validate::<crate::kinds::Settings>(json)
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Returns the registered `SettingsDefinition`.
    ///
    /// # Errors
    ///
    /// `unknownContent` when the project declares no settings declaration.
    pub fn settings(&self) -> JsonResult {
        let value = self
            .inner
            .only::<crate::kinds::Settings>()
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Resolves values against the declaration: defaults filled, unknown keys
    /// dropped, numbers clamped. Returns the resolved object.
    ///
    /// # Errors
    ///
    /// `parse` when the values are not a JSON object.
    pub fn resolve_settings(&self, values_json: &str) -> JsonResult {
        let value = self
            .inner
            .resolved_settings(values_json)
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Parses, validates and registers a character definition. Returns a
    /// [`LoadOutcome`](crate::LoadOutcome).
    ///
    /// # Errors
    ///
    /// `parse` for malformed JSON, `invalidContent` for a failing character
    /// definition.
    pub fn load_character(&mut self, json: &str) -> JsonResult {
        let value = self
            .inner
            .load::<crate::kinds::Character>(json)
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Validates a character definition **without** registering it, keys
    /// included. Returns a `ValidationReport`.
    ///
    /// # Errors
    ///
    /// `parse` for malformed JSON.
    pub fn validate_character(&self, json: &str) -> JsonResult {
        let value = self
            .inner
            .validate::<crate::kinds::Character>(json)
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Returns a registered
    /// [`CharacterDefinition`](insulaire_world::CharacterDefinition).
    ///
    /// # Errors
    ///
    /// `unknownContent` when no definition has that id.
    pub fn character(&self, id: &str) -> JsonResult {
        let value = self
            .inner
            .definition::<crate::kinds::Character>(id)
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Returns the ids of every registered character definition.
    ///
    /// # Errors
    ///
    /// Only on serialisation failure.
    pub fn character_ids(&self) -> JsonResult {
        ok(&self.inner.ids::<crate::kinds::Character>())
    }

    /// Parses, validates and registers a decoration definition. Returns a
    /// [`LoadOutcome`](crate::LoadOutcome).
    ///
    /// # Errors
    ///
    /// `parse` for malformed JSON, `invalidContent` for a failing decoration
    /// definition.
    pub fn load_decoration(&mut self, json: &str) -> JsonResult {
        let value = self
            .inner
            .load::<crate::kinds::Decoration>(json)
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Returns a registered
    /// [`DecorationDefinition`](insulaire_world::DecorationDefinition).
    ///
    /// # Errors
    ///
    /// `unknownContent` when no definition has that id.
    pub fn decoration(&self, id: &str) -> JsonResult {
        let value = self
            .inner
            .definition::<crate::kinds::Decoration>(id)
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Returns the ids of every registered decoration definition.
    ///
    /// # Errors
    ///
    /// Only on serialisation failure.
    pub fn decoration_ids(&self) -> JsonResult {
        ok(&self.inner.ids::<crate::kinds::Decoration>())
    }

    /// Validates a decoration definition *without* registering it. Returns a
    /// `ValidationReport`.
    ///
    /// `cell_json` is the `TileArtGeometry` it will stand among; `""` skips
    /// `decoration.overflowsCell` alone.
    ///
    /// # Errors
    ///
    /// `parse` when either JSON is malformed.
    pub fn validate_decoration(&self, json: &str, cell_json: &str) -> JsonResult {
        let value = self
            .inner
            .validate_decoration(json, cell_json)
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Resolves a registered decoration at a moment of one of its animations.
    /// Returns a `ResolvedDecoration`.
    ///
    /// # Errors
    ///
    /// `unknownContent` when no definition has that id.
    pub fn resolve_decoration(
        &self,
        id: &str,
        animation: Option<&str>,
        time_ms: u32,
    ) -> JsonResult {
        let value = self
            .inner
            .resolve_decoration(id, animation, time_ms)
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Resolves a decoration definition passed in by the editor.
    ///
    /// # Errors
    ///
    /// `parse` when the JSON is malformed.
    pub fn preview_decoration(
        &self,
        decoration_json: &str,
        animation: Option<&str>,
        time_ms: u32,
    ) -> JsonResult {
        let value = self
            .inner
            .preview_decoration(decoration_json, animation, time_ms)
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Parses, validates and registers an object definition. Returns a
    /// [`LoadOutcome`](crate::LoadOutcome).
    ///
    /// # Errors
    ///
    /// `parse` for malformed JSON, `invalidContent` for a failing object
    /// definition.
    pub fn load_object(&mut self, json: &str) -> JsonResult {
        let value = self
            .inner
            .load::<crate::kinds::Object>(json)
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Validates an object definition **without** registering it, keys
    /// included. Returns a `ValidationReport`.
    ///
    /// # Errors
    ///
    /// `parse` for malformed JSON.
    pub fn validate_object(&self, json: &str) -> JsonResult {
        let value = self
            .inner
            .validate::<crate::kinds::Object>(json)
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Returns a registered
    /// [`ObjectDefinition`](insulaire_world::ObjectDefinition).
    ///
    /// # Errors
    ///
    /// `unknownContent` when no definition has that id.
    pub fn object(&self, id: &str) -> JsonResult {
        let value = self
            .inner
            .definition::<crate::kinds::Object>(id)
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Returns the ids of every registered object definition.
    ///
    /// # Errors
    ///
    /// Only on serialisation failure.
    pub fn object_ids(&self) -> JsonResult {
        ok(&self.inner.ids::<crate::kinds::Object>())
    }

    /// Resolves a registered object's icon at a moment of its flipbook. Returns
    /// a `ResolvedObject`.
    ///
    /// # Errors
    ///
    /// `unknownContent` when no definition has that id.
    pub fn resolve_object(&self, id: &str, time_ms: u32) -> JsonResult {
        let value = self
            .inner
            .resolve_object(id, time_ms)
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Resolves an object definition passed in by the editor.
    ///
    /// # Errors
    ///
    /// `parse` when the JSON is malformed.
    pub fn preview_object(&self, object_json: &str, time_ms: u32) -> JsonResult {
        let value = self
            .inner
            .preview_object(object_json, time_ms)
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Parses, validates and registers a generic character-creation
    /// declaration. Character definitions must be loaded first.
    ///
    /// # Errors
    ///
    /// `parse` for malformed JSON, `invalidContent` for a declaration that
    /// cannot be shown.
    pub fn load_character_creation(&mut self, json: &str) -> JsonResult {
        let value = self
            .inner
            .load::<crate::kinds::CharacterCreation>(json)
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Validates a character-creation declaration without registering it.
    ///
    /// # Errors
    ///
    /// `parse` for malformed JSON.
    pub fn validate_character_creation(&self, json: &str) -> JsonResult {
        let value = self
            .inner
            .validate::<crate::kinds::CharacterCreation>(json)
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Returns the registered `CharacterCreationDefinition`.
    ///
    /// # Errors
    ///
    /// `unknownContent` when the project declares no character-creation
    /// declaration.
    pub fn character_creation(&self) -> JsonResult {
        let value = self
            .inner
            .only::<crate::kinds::CharacterCreation>()
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Resolves submitted creation choices and characteristics without
    /// interpreting any author-owned id.
    ///
    /// # Errors
    ///
    /// `parse` when either values payload is not JSON, `unknownContent` when no
    /// declaration is loaded.
    pub fn resolve_character_creation(
        &self,
        choices_json: &str,
        characteristics_json: &str,
    ) -> JsonResult {
        let value = self
            .inner
            .resolved_character_creation(choices_json, characteristics_json)
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Resolves a creation definition passed in by the editor.
    ///
    /// # Errors
    ///
    /// `parse` when any of the three arguments is not JSON.
    pub fn preview_character_creation(
        &self,
        creation_json: &str,
        choices_json: &str,
        characteristics_json: &str,
    ) -> JsonResult {
        let value = self
            .inner
            .preview_character_creation(creation_json, choices_json, characteristics_json)
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Resolves a definition **passed in** against a customisation, at a moment
    /// of an animation — the editor's preview, for content that is not
    /// registered yet. Returns a
    /// [`ResolvedCharacter`](insulaire_world::ResolvedCharacter).
    ///
    /// `animation` of `undefined` — or an id the definition does not declare —
    /// is the rest pose. `time_ms` counts from the start of the animation.
    ///
    /// # Errors
    ///
    /// `parse` when either argument is not JSON.
    pub fn preview_character(
        &self,
        character_json: &str,
        values_json: &str,
        animation: Option<&str>,
        time_ms: u32,
    ) -> JsonResult {
        let value = self
            .inner
            .preview_character(character_json, values_json, animation, time_ms)
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Resolves a definition against a customisation such as
    /// `{"hairColor":"#f2c14e"}`, at a moment of an animation. Returns a
    /// [`ResolvedCharacter`](insulaire_world::ResolvedCharacter).
    ///
    /// # Errors
    ///
    /// `parse` when the values are not JSON, `unknownContent` when no
    /// definition has that id.
    pub fn resolve_character(
        &self,
        id: &str,
        values_json: &str,
        animation: Option<&str>,
        time_ms: u32,
    ) -> JsonResult {
        let value = self
            .inner
            .resolve_character(id, values_json, animation, time_ms)
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Resolves the animation assigned to a gameplay role such as `idle` or
    /// `moveNorthWest`. Exact movement directions fall back to the authored
    /// left/right roles when absent.
    ///
    /// # Errors
    ///
    /// `parse` for an unknown role or malformed values, `unknownContent` when
    /// no definition has that id.
    pub fn resolve_character_role(
        &self,
        id: &str,
        values_json: &str,
        role: &str,
        time_ms: u32,
    ) -> JsonResult {
        let role = role.parse().map_err(|message| {
            err(&EngineError::Parse {
                what: "character animation role".to_owned(),
                message,
            })
        })?;
        let value = self
            .inner
            .resolve_character_role(id, values_json, role, time_ms)
            .map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Returns the current [`GameSnapshot`](crate::GameSnapshot).
    ///
    /// # Errors
    ///
    /// `noGame` when nothing is running.
    pub fn snapshot(&self) -> JsonResult {
        let value = self.inner.snapshot().map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Applies a command such as `{"type":"moveTo","to":[3,4]}` or
    /// `{"type":"wait"}`. Returns a [`CommandResult`](crate::CommandResult).
    ///
    /// An *illegal* command is not an error: it comes back with `accepted:
    /// false` and a `rejection`.
    ///
    /// # Errors
    ///
    /// `parse` for an unknown command shape, `noGame` when nothing is running.
    pub fn dispatch(&mut self, command_json: &str) -> JsonResult {
        let command: Command = serde_json::from_str(command_json).map_err(|error| {
            err(&EngineError::Parse {
                what: "command".to_owned(),
                message: error.to_string(),
            })
        })?;
        let value = self.inner.dispatch(command).map_err(|error| err(&error))?;
        ok(&value)
    }

    /// Discards the running game. Content stays loaded.
    pub fn end_game(&mut self) {
        self.inner.end_game();
    }

    /// `true` when a game is in progress.
    #[must_use]
    pub const fn has_game(&self) -> bool {
        self.inner.has_game()
    }
}

#[cfg(test)]
mod tests;
