[package]
name = "hex-wasm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
description = "WebAssembly bindings for the hex engine."
keywords.workspace = true
categories.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[lints.rust]
missing_docs = "warn"

[dependencies]
hex-engine = { workspace = true }
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"
