// @generated by `node scripts/generate-seam.mjs` from `crates/engine/seam.json`.
// Edit the declaration, not this file — `npm run check:seam` fails on a stale copy.

//! WebAssembly bindings for the hex engine.
//!
//! This crate contains **no game logic and no boundary logic**. The string
//! contract — JSON in, JSON out, errors as serialised `EngineErrorPayload` —
//! lives in [`insulaire_engine::JsonEngine`], where it is covered by ordinary
//! `cargo test`. Everything here is a one-line pass-through that converts
//! `String` errors into `JsValue`.
//!
//! That split is deliberate: a bug in the boundary should be catchable without
//! a browser. See `docs/wasm-api.md` and `docs/adr/ADR-0010-engine-api.md`.

#![forbid(unsafe_code)]

use insulaire_engine::JsonEngine;
use wasm_bindgen::prelude::*;

/// Installs a panic hook so Rust panics surface as readable console errors
/// instead of `unreachable executed`.
#[wasm_bindgen(start)]
pub fn start() {
    console_error_panic_hook::set_once();
}

fn to_js(error: String) -> JsValue {
    JsValue::from_str(&error)
}

/// The engine, as seen from JavaScript.
///
/// One instance owns one content registry and at most one running game.
/// Every method that can fail rejects with a JSON string of the shape
/// `{ "code": "...", "message": "...", "report"?: { ... } }`.
#[wasm_bindgen]
#[derive(Debug, Default)]
pub struct InsulaireEngine {
    inner: JsonEngine,
}

#[wasm_bindgen]
impl InsulaireEngine {
    /// Creates an engine with an empty content registry.
    #[wasm_bindgen(constructor)]
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Build identity: name, version, target architecture, pointer width and
    /// supported schema versions.
    ///
    /// # Errors
    ///
    /// Only on serialisation failure.
    #[wasm_bindgen(js_name = engineInfo)]
    pub fn engine_info(&self) -> Result<String, JsValue> {
        self.inner.engine_info().map_err(to_js)
    }

    /// Parses, validates and registers a tile set. Returns a `LoadOutcome`.
    ///
    /// # Errors
    ///
    /// `parse` for malformed JSON, `invalidContent` for a failing tile set.
    #[wasm_bindgen(js_name = loadTileSet)]
    pub fn load_tile_set(&mut self, json: &str) -> Result<String, JsValue> {
        self.inner.load_tile_set(json).map_err(to_js)
    }

    /// Parses, validates and registers a world. Returns a `LoadOutcome`.
    ///
    /// # Errors
    ///
    /// `parse` for malformed JSON, `invalidContent` for a failing world. The
    /// error payload carries the full validation report.
    #[wasm_bindgen(js_name = loadWorld)]
    pub fn load_world(&mut self, json: &str) -> Result<String, JsValue> {
        self.inner.load_world(json).map_err(to_js)
    }

    /// Parses, validates and registers the project manifest — the list of
    /// content files that make up the game, and the world it starts on. Returns
    /// a `LoadOutcome`.
    ///
    /// Call it after the content it lists has been loaded.
    ///
    /// # Errors
    ///
    /// `parse` for malformed JSON, `invalidContent` when it references content
    /// that is not loaded.
    #[wasm_bindgen(js_name = loadProject)]
    pub fn load_project(&mut self, json: &str) -> Result<String, JsValue> {
        self.inner.load_project(json).map_err(to_js)
    }

    /// Registers one locale file under a language and a namespace. Returns a
    /// `LoadOutcome` whose id is `language/namespace`.
    ///
    /// # Errors
    ///
    /// `parse` when the file is not a nested object of strings, or redefines a
    /// key the language already has.
    #[wasm_bindgen(js_name = loadLocale)]
    pub fn load_locale(
        &mut self,
        language: &str,
        namespace: &str,
        json: &str,
    ) -> Result<String, JsValue> {
        self.inner
            .load_locale(language, namespace, json)
            .map_err(to_js)
    }

    /// Returns a `LocaleView`: one language's text, gaps filled by the default
    /// language.
    ///
    /// # Errors
    ///
    /// `unknownContent` when no file was loaded for that language.
    #[wasm_bindgen(js_name = locale)]
    pub fn locale(&self, language: &str) -> Result<String, JsValue> {
        self.inner.locale(language).map_err(to_js)
    }

    /// Compares the loaded languages against the manifest and each other.
    /// Returns a `ValidationReport`.
    ///
    /// # Errors
    ///
    /// Only on serialisation failure.
    #[wasm_bindgen(js_name = validateLocales)]
    pub fn validate_locales(&self) -> Result<String, JsValue> {
        self.inner.validate_locales().map_err(to_js)
    }

    /// Registers the title screen a client opens on. Returns a `LoadOutcome`.
    ///
    /// # Errors
    ///
    /// `parse` for malformed JSON, `invalidContent` for a screen that cannot be
    /// shown — no visible `newGame` button, an asset path leaving the content
    /// root, a number out of range.
    #[wasm_bindgen(js_name = loadTitleScreen)]
    pub fn load_title_screen(&mut self, json: &str) -> Result<String, JsValue> {
        self.inner.load_title_screen(json).map_err(to_js)
    }

    /// Validates a title screen *without* registering it, keys included.
    /// Returns a `ValidationReport`.
    ///
    /// # Errors
    ///
    /// `parse` for malformed JSON.
    #[wasm_bindgen(js_name = validateTitleScreen)]
    pub fn validate_title_screen(&self, json: &str) -> Result<String, JsValue> {
        self.inner.validate_title_screen(json).map_err(to_js)
    }

    /// Validates a tile set **without** registering it. Returns a
    /// `ValidationReport`.
    ///
    /// # Errors
    ///
    /// `parse` for malformed JSON.
    #[wasm_bindgen(js_name = validateTileSet)]
    pub fn validate_tile_set(&self, json: &str) -> Result<String, JsValue> {
        self.inner.validate_tile_set(json).map_err(to_js)
    }

    /// Resolves what to draw for one cell of a tile set **passed in** — the
    /// asset editor's preview, for content that is not registered yet. Returns
    /// a `ResolvedTileRender`.
    ///
    /// `base` is the height the cell's side faces reach down to; `roll` is the
    /// cell's variant roll
    /// (`docs/adr/ADR-0026-tile-art-is-authored-and-resolved-by-level.md`).
    /// `projection` is the world's own — `"isometric"` for the surface and the
    /// cliff, anything else for the flat image
    /// (`docs/adr/ADR-0026-tile-art-is-authored-and-resolved-by-level.md`).
    /// `choice_json` is a `PlacedTileArt` — what the cell picked by hand —
    /// resolved against the set passed in; `"{}"` rolls everything
    /// (`docs/adr/ADR-0026-tile-art-is-authored-and-resolved-by-level.md`).
    ///
    /// # Errors
    ///
    /// `parse` when either JSON is malformed, `unknownContent` when the set
    /// defines no tile with that id.
    #[wasm_bindgen(js_name = previewTileRender)]
    #[allow(clippy::too_many_arguments)] // a wire, not an API: every field the boundary carries is a parameter
    pub fn preview_tile_render(
        &self,
        tile_set_json: &str,
        tile_id: &str,
        projection: &str,
        elevation: i32,
        base: i32,
        roll: u32,
        choice_json: &str,
    ) -> Result<String, JsValue> {
        self.inner
            .preview_tile_render(
                tile_set_json,
                tile_id,
                projection,
                elevation,
                base,
                roll,
                choice_json,
            )
            .map_err(to_js)
    }

    /// Returns the registered `TitleScreenDefinition`.
    ///
    /// # Errors
    ///
    /// `unknownContent` when the project ships no title screen.
    #[wasm_bindgen(js_name = titleScreen)]
    pub fn title_screen(&self) -> Result<String, JsValue> {
        self.inner.title_screen().map_err(to_js)
    }

    /// Forgets every loaded tile set, world, locale and project.
    ///
    /// Hosts call this before re-loading a whole project, so content removed in
    /// the editor stops answering for itself. A running game is unaffected.
    #[wasm_bindgen(js_name = resetContent)]
    pub fn reset_content(&mut self) {
        self.inner.reset_content();
    }

    /// Forgets every loaded language, keeping worlds, tile sets and project.
    ///
    /// The language editor calls this before registering the files it just
    /// wrote: loading is additive and refuses a key twice, so edited text can
    /// only replace the old text once the old bundles are gone.
    #[wasm_bindgen(js_name = resetLocales)]
    pub fn reset_locales(&mut self) {
        self.inner.reset_locales();
    }

    /// Resolves every map link across the loaded worlds. Returns a
    /// `ValidationReport`.
    ///
    /// # Errors
    ///
    /// Only on serialisation failure.
    #[wasm_bindgen(js_name = validateLinks)]
    pub fn validate_links(&self) -> Result<String, JsValue> {
        self.inner.validate_links().map_err(to_js)
    }

    /// Validates a world *without* registering it — the editor's pre-export
    /// check. Returns a `ValidationReport`.
    ///
    /// # Errors
    ///
    /// `parse` for malformed JSON. An unusable world yields an invalid report,
    /// not an error.
    #[wasm_bindgen(js_name = validateWorld)]
    pub fn validate_world(&self, json: &str) -> Result<String, JsValue> {
        self.inner.validate_world(json).map_err(to_js)
    }

    /// Returns a `ContentSummary`: loaded tile sets, worlds and templates.
    ///
    /// # Errors
    ///
    /// Only on serialisation failure.
    #[wasm_bindgen(js_name = contentSummary)]
    pub fn content_summary(&self) -> Result<String, JsValue> {
        self.inner.content_summary().map_err(to_js)
    }

    /// Returns a `WorldView`: dimensions, tile palette and locations.
    ///
    /// # Errors
    ///
    /// `unknownContent` when the world is not registered.
    #[wasm_bindgen(js_name = worldView)]
    pub fn world_view(&self, world_id: &str) -> Result<String, JsValue> {
        self.inner.world_view(world_id).map_err(to_js)
    }

    /// Returns the packed terrain buffer as a `Uint8Array`: one palette index
    /// per cell, row-major in offset coordinates.
    ///
    /// This is one of the three bulk transfers in the API, and the reason the
    /// renderer never calls into WASM per tile.
    ///
    /// # Errors
    ///
    /// `unknownContent` when the world is not registered.
    #[wasm_bindgen(js_name = terrainBuffer)]
    pub fn terrain_buffer(&self, world_id: &str) -> Result<Vec<u8>, JsValue> {
        self.inner.terrain_buffer(world_id).map_err(to_js)
    }

    /// Returns the packed elevation buffer as an `Int8Array`: one signed byte
    /// per cell, in the same layout as `terrainBuffer`.
    ///
    /// Presentation only; the renderer uses it in isometric mode
    /// (`docs/adr/ADR-0013-isometric-projection.md`).
    ///
    /// # Errors
    ///
    /// `unknownContent` when the world is not registered.
    #[wasm_bindgen(js_name = elevationBuffer)]
    pub fn elevation_buffer(&self, world_id: &str) -> Result<Vec<i8>, JsValue> {
        self.inner.elevation_buffer(world_id).map_err(to_js)
    }

    /// Returns the packed presence buffer as a `Uint8Array`: `1` where the map
    /// has a hex, `0` where it has a hole, in the same layout as
    /// `terrainBuffer`.
    ///
    /// A map is a set of hexes, not a rectangle; the extent in
    /// `worldView().bounds` is only what the buffers cover
    /// (`docs/adr/ADR-0033-a-map-is-a-set-of-hexes.md`).
    ///
    /// # Errors
    ///
    /// `unknownContent` when the world is not registered.
    #[wasm_bindgen(js_name = presenceBuffer)]
    pub fn presence_buffer(&self, world_id: &str) -> Result<Vec<u8>, JsValue> {
        self.inner.presence_buffer(world_id).map_err(to_js)
    }

    /// Starts a game on a registered world. Returns the initial `GameSnapshot`.
    ///
    /// # Errors
    ///
    /// `unknownContent` or `setup`.
    #[wasm_bindgen(js_name = createGame)]
    pub fn create_game(
        &mut self,
        world_id: &str,
        seed: u32,
        settings_json: &str,
    ) -> Result<String, JsValue> {
        self.inner
            .create_game(world_id, seed, settings_json)
            .map_err(to_js)
    }

    /// Registers the game's settings declaration. Returns a `LoadOutcome`.
    ///
    /// # Errors
    ///
    /// `parse` for malformed JSON, `invalidContent` for a declaration that
    /// cannot be rendered — a duplicate id, a default no control accepts.
    #[wasm_bindgen(js_name = loadSettings)]
    pub fn load_settings(&mut self, json: &str) -> Result<String, JsValue> {
        self.inner.load_settings(json).map_err(to_js)
    }

    /// Validates a settings declaration *without* registering it, keys
    /// included. Returns a `ValidationReport`.
    ///
    /// # Errors
    ///
    /// `parse` for malformed JSON.
    #[wasm_bindgen(js_name = validateSettings)]
    pub fn validate_settings(&self, json: &str) -> Result<String, JsValue> {
        self.inner.validate_settings(json).map_err(to_js)
    }

    /// Returns the registered `SettingsDefinition`.
    ///
    /// # Errors
    ///
    /// `unknownContent` when the project declares no settings.
    #[wasm_bindgen(js_name = settings)]
    pub fn settings(&self) -> Result<String, JsValue> {
        self.inner.settings().map_err(to_js)
    }

    /// Resolves values against the declaration: defaults filled, unknown keys
    /// dropped, numbers clamped. Returns the resolved object.
    ///
    /// # Errors
    ///
    /// `parse` when the values are not a JSON object.
    #[wasm_bindgen(js_name = resolveSettings)]
    pub fn resolve_settings(&self, values_json: &str) -> Result<String, JsValue> {
        self.inner.resolve_settings(values_json).map_err(to_js)
    }

    /// Parses, validates and registers a character definition. Returns a
    /// `LoadOutcome`.
    ///
    /// # Errors
    ///
    /// `parse` for malformed JSON, `invalidContent` for a failing definition.
    #[wasm_bindgen(js_name = loadCharacter)]
    pub fn load_character(&mut self, json: &str) -> Result<String, JsValue> {
        self.inner.load_character(json).map_err(to_js)
    }

    /// Validates a character definition *without* registering it, keys
    /// included. Returns a `ValidationReport`.
    ///
    /// # Errors
    ///
    /// `parse` when the JSON is malformed.
    #[wasm_bindgen(js_name = validateCharacter)]
    pub fn validate_character(&self, json: &str) -> Result<String, JsValue> {
        self.inner.validate_character(json).map_err(to_js)
    }

    /// Returns a registered `CharacterDefinition`.
    ///
    /// # Errors
    ///
    /// `unknownContent` when no definition has that id.
    #[wasm_bindgen(js_name = character)]
    pub fn character(&self, id: &str) -> Result<String, JsValue> {
        self.inner.character(id).map_err(to_js)
    }

    /// Returns the ids of every registered character definition.
    ///
    /// # Errors
    ///
    /// Only on serialisation failure.
    #[wasm_bindgen(js_name = characterIds)]
    pub fn character_ids(&self) -> Result<String, JsValue> {
        self.inner.character_ids().map_err(to_js)
    }

    /// Parses, validates and registers a decoration definition. Returns a
    /// `LoadOutcome`.
    ///
    /// # Errors
    ///
    /// `parse` for malformed JSON, `invalidContent` for a failing definition.
    #[wasm_bindgen(js_name = loadDecoration)]
    pub fn load_decoration(&mut self, json: &str) -> Result<String, JsValue> {
        self.inner.load_decoration(json).map_err(to_js)
    }

    /// Validates a decoration definition *without* registering it. Returns a
    /// `ValidationReport`.
    ///
    /// `cell_json` is the `TileArtGeometry` it will stand among; `""` skips
    /// `decoration.overflowsCell` alone.
    ///
    /// # Errors
    ///
    /// `parse` when either JSON is malformed.
    #[wasm_bindgen(js_name = validateDecoration)]
    pub fn validate_decoration(&self, json: &str, cell_json: &str) -> Result<String, JsValue> {
        self.inner
            .validate_decoration(json, cell_json)
            .map_err(to_js)
    }

    /// Returns a registered `DecorationDefinition`.
    ///
    /// # Errors
    ///
    /// `unknownContent` when no definition has that id.
    #[wasm_bindgen(js_name = decoration)]
    pub fn decoration(&self, id: &str) -> Result<String, JsValue> {
        self.inner.decoration(id).map_err(to_js)
    }

    /// Returns the ids of every registered decoration definition.
    ///
    /// # Errors
    ///
    /// Only on serialisation failure.
    #[wasm_bindgen(js_name = decorationIds)]
    pub fn decoration_ids(&self) -> Result<String, JsValue> {
        self.inner.decoration_ids().map_err(to_js)
    }

    /// Resolves a registered decoration at a moment of one of its animations.
    /// Returns a `ResolvedDecoration`.
    ///
    /// # Errors
    ///
    /// `unknownContent` when no definition has that id.
    #[wasm_bindgen(js_name = resolveDecoration)]
    pub fn resolve_decoration(
        &self,
        id: &str,
        animation: Option<String>,
        time_ms: u32,
    ) -> Result<String, JsValue> {
        self.inner
            .resolve_decoration(id, animation.as_deref(), time_ms)
            .map_err(to_js)
    }

    /// Resolves a decoration definition passed in by the editor.
    ///
    /// # Errors
    ///
    /// `parse` when the JSON is malformed.
    #[wasm_bindgen(js_name = previewDecoration)]
    pub fn preview_decoration(
        &self,
        decoration_json: &str,
        animation: Option<String>,
        time_ms: u32,
    ) -> Result<String, JsValue> {
        self.inner
            .preview_decoration(decoration_json, animation.as_deref(), time_ms)
            .map_err(to_js)
    }

    /// Parses, validates and registers an object definition. Returns a
    /// `LoadOutcome`.
    ///
    /// # Errors
    ///
    /// `parse` for malformed JSON, `invalidContent` for a failing definition.
    #[wasm_bindgen(js_name = loadObject)]
    pub fn load_object(&mut self, json: &str) -> Result<String, JsValue> {
        self.inner.load_object(json).map_err(to_js)
    }

    /// Validates an object definition *without* registering it, keys included.
    /// Returns a `ValidationReport`.
    ///
    /// # Errors
    ///
    /// `parse` when the JSON is malformed.
    #[wasm_bindgen(js_name = validateObject)]
    pub fn validate_object(&self, json: &str) -> Result<String, JsValue> {
        self.inner.validate_object(json).map_err(to_js)
    }

    /// Returns a registered `ObjectDefinition`.
    ///
    /// # Errors
    ///
    /// `unknownContent` when no definition has that id.
    #[wasm_bindgen(js_name = object)]
    pub fn object(&self, id: &str) -> Result<String, JsValue> {
        self.inner.object(id).map_err(to_js)
    }

    /// Returns the ids of every registered object definition.
    ///
    /// # Errors
    ///
    /// Only on serialisation failure.
    #[wasm_bindgen(js_name = objectIds)]
    pub fn object_ids(&self) -> Result<String, JsValue> {
        self.inner.object_ids().map_err(to_js)
    }

    /// Resolves a registered object's icon at a moment of its flipbook. Returns
    /// a `ResolvedObject`.
    ///
    /// # Errors
    ///
    /// `unknownContent` when no definition has that id.
    #[wasm_bindgen(js_name = resolveObject)]
    pub fn resolve_object(&self, id: &str, time_ms: u32) -> Result<String, JsValue> {
        self.inner.resolve_object(id, time_ms).map_err(to_js)
    }

    /// Resolves an object definition passed in by the editor.
    ///
    /// # Errors
    ///
    /// `parse` when the JSON is malformed.
    #[wasm_bindgen(js_name = previewObject)]
    pub fn preview_object(&self, object_json: &str, time_ms: u32) -> Result<String, JsValue> {
        self.inner
            .preview_object(object_json, time_ms)
            .map_err(to_js)
    }

    /// Parses, validates and registers a generic character-creation
    /// declaration. Character definitions must be loaded first.
    ///
    /// # Errors
    ///
    /// `parse` for malformed JSON, `invalidContent` for a declaration that
    /// cannot be shown.
    #[wasm_bindgen(js_name = loadCharacterCreation)]
    pub fn load_character_creation(&mut self, json: &str) -> Result<String, JsValue> {
        self.inner.load_character_creation(json).map_err(to_js)
    }

    /// Validates a character-creation declaration without registering it.
    ///
    /// # Errors
    ///
    /// `parse` when the JSON is malformed.
    #[wasm_bindgen(js_name = validateCharacterCreation)]
    pub fn validate_character_creation(&self, json: &str) -> Result<String, JsValue> {
        self.inner.validate_character_creation(json).map_err(to_js)
    }

    /// Returns the registered `CharacterCreationDefinition`.
    ///
    /// # Errors
    ///
    /// `unknownContent` when the project declares none.
    #[wasm_bindgen(js_name = characterCreation)]
    pub fn character_creation(&self) -> Result<String, JsValue> {
        self.inner.character_creation().map_err(to_js)
    }

    /// Resolves submitted creation choices and characteristics without
    /// interpreting any author-owned id.
    ///
    /// # Errors
    ///
    /// `parse` when either values payload is not JSON, `unknownContent` when no
    /// declaration is loaded.
    #[wasm_bindgen(js_name = resolveCharacterCreation)]
    pub fn resolve_character_creation(
        &self,
        choices_json: &str,
        characteristics_json: &str,
    ) -> Result<String, JsValue> {
        self.inner
            .resolve_character_creation(choices_json, characteristics_json)
            .map_err(to_js)
    }

    /// Resolves a creation definition passed in by the editor.
    ///
    /// # Errors
    ///
    /// `parse` when any of the three arguments is not JSON.
    #[wasm_bindgen(js_name = previewCharacterCreation)]
    pub fn preview_character_creation(
        &self,
        creation_json: &str,
        choices_json: &str,
        characteristics_json: &str,
    ) -> Result<String, JsValue> {
        self.inner
            .preview_character_creation(creation_json, choices_json, characteristics_json)
            .map_err(to_js)
    }

    /// Resolves a definition **passed in** against a customisation, at a moment
    /// of an animation — the editor's preview, for content that is not
    /// registered yet. Returns a `ResolvedCharacter`.
    ///
    /// `animation` of `undefined` — or an id the definition does not declare —
    /// is the rest pose. `time_ms` counts from the start of the animation.
    ///
    /// # Errors
    ///
    /// `parse` when either argument is not JSON.
    #[wasm_bindgen(js_name = previewCharacter)]
    pub fn preview_character(
        &self,
        character_json: &str,
        values_json: &str,
        animation: Option<String>,
        time_ms: u32,
    ) -> Result<String, JsValue> {
        self.inner
            .preview_character(character_json, values_json, animation.as_deref(), time_ms)
            .map_err(to_js)
    }

    /// Resolves a definition against a customisation such as
    /// `{"hairColor":"#f2c14e"}`, at a moment of an animation. Returns a
    /// `ResolvedCharacter`.
    ///
    /// # Errors
    ///
    /// `parse` when the values are not JSON, `unknownContent` when no
    /// definition has that id.
    #[wasm_bindgen(js_name = resolveCharacter)]
    pub fn resolve_character(
        &self,
        id: &str,
        values_json: &str,
        animation: Option<String>,
        time_ms: u32,
    ) -> Result<String, JsValue> {
        self.inner
            .resolve_character(id, values_json, animation.as_deref(), time_ms)
            .map_err(to_js)
    }

    /// Resolves the animation assigned to a gameplay role such as `idle` or
    /// `moveNorthWest`. Exact movement directions fall back to the authored
    /// left/right roles when absent.
    ///
    /// # Errors
    ///
    /// `parse` for an unknown role or malformed values, `unknownContent` when
    /// no definition has that id.
    #[wasm_bindgen(js_name = resolveCharacterRole)]
    pub fn resolve_character_role(
        &self,
        id: &str,
        values_json: &str,
        role: &str,
        time_ms: u32,
    ) -> Result<String, JsValue> {
        self.inner
            .resolve_character_role(id, values_json, role, time_ms)
            .map_err(to_js)
    }

    /// Returns the current `GameSnapshot`.
    ///
    /// # Errors
    ///
    /// `noGame` when nothing is running.
    #[wasm_bindgen(js_name = snapshot)]
    pub fn snapshot(&self) -> Result<String, JsValue> {
        self.inner.snapshot().map_err(to_js)
    }

    /// Applies a command such as `{"type":"moveTo","to":[3,4]}` or
    /// `{"type":"wait"}`. Returns a `CommandResult`.
    ///
    /// An *illegal* command is not an error: it comes back with `accepted:
    /// false` and a `rejection`.
    ///
    /// # Errors
    ///
    /// `parse` for an unknown command shape, `noGame` when nothing is running.
    #[wasm_bindgen(js_name = dispatch)]
    pub fn dispatch(&mut self, command_json: &str) -> Result<String, JsValue> {
        self.inner.dispatch(command_json).map_err(to_js)
    }

    /// Discards the running game. Content stays loaded.
    #[wasm_bindgen(js_name = endGame)]
    pub fn end_game(&mut self) {
        self.inner.end_game();
    }

    /// `true` when a game is in progress.
    #[wasm_bindgen(js_name = hasGame)]
    #[must_use]
    pub fn has_game(&self) -> bool {
        self.inner.has_game()
    }
}
